// <auto-generated />
using Hotsite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hotsite.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230711210223_CriarBancoDados")]
    partial class CriarBancoDados
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Hotsite.Models.Interesse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .HasMaxLength(156);

                    b.Property<string>("Mensagem")
                        .HasMaxLength(512);

                    b.Property<string>("Nome")
                        .HasMaxLength(156);

                    b.HasKey("Id");

                    b.ToTable("Interesses");
                });
#pragma warning restore 612, 618
        }
    }
}
